### PR TITLE
Added an option to copy data only and no mapping.

### PR DESCRIPTION
**Pull request by dmcqueen**

### CODE REVIEW

**Comment by mallocator** [comment]
Thanks for the patch. I never considered this requirement. I'll port it to 2.0 as well.

**Comment by dmcqueen** [comment]
No problem.  It's useful for migrating data to a new schema when you want to change field types or indexing options in the mapping.

**Comment by mallocator** [comment]
For that I added the  ```--mapping``` option with which you can define whatever mapping you want to have. I figured you can use that to set an empty mapping and not overwrite the existing one, but my thought was that it might be easier for someone to use your added option if they just don't want to touch the mapping and skip that step completely (in v2.0 I can probably also skip the fetch step and make it overall a little faster).

**Comment by dmcqueen** [comment]
I saw that option but was already defining my mapping earlier in the migration process so just made more sense to do it once.

**Pull request merged**
